name: Update World Cup Scores

on:
  schedule:
    # GitHub käyttää UTC-aikaa. Suomi on UTC+3 (kesäisin).
    # Tämä skripti ajetaan joka päivä 4 kertaa: klo 12:22, 15:22, 18:22 ja 21:22 UTC-aikaa, mikä vastaa 15:22, 18:22, 21:22 ja 00:22 Suomen aikaa.
    - cron: "22 12,15,18,21 * * *" # Aja joka päivä klo 12:22, 15:22, 18:22 ja 21:22 UTC-aikaa
  workflow_dispatch: # Mahdollistaa ajon käsin GitHubin UI:sta

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install playwright pymongo dotenv pytz
          playwright install chromium

      - name: Run update script
        env:
          # Lisää nämä GitHub Secretsiin!
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          python scraping/movingdata.py
